name: kolektix
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.8
  dio: ^4.0.6
  fluttertoast: ^8.0.9
  flutter_verification_code: ^1.1.7
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: InterRegular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: InterBold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
    - family: NotoSansRegular
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
    - family: NotoSansBold
      fonts:
        - asset: assets/fonts/NotoSans-Bold.ttf
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

