name: kolektix
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.8
  dio: ^4.0.6
  fluttertoast: ^8.0.9
  flutter_verification_code: ^1.1.7
  google_maps_flutter: ^2.1.0
  image_picker: ^1.0.7
  calendar_date_picker2: ^1.0.2
  dotted_line: ^3.2.2
  shared_preferences: ^2.2.2
  flutter_timer_countdown: ^1.0.7
  file_picker: ^6.2.0
  js: ^0.7.1
  web: ^1.1.0
  flutter_html: ^3.0.0-beta.2
  http: ^1.2.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: InterRegular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: InterBold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
    - family: NotoSansRegular
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
    - family: NotoSansBold
      fonts:
        - asset: assets/fonts/NotoSans-Bold.ttf
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

